;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from minor-modes/dumb-indent-mode.el

(register-definition-prefixes "minor-modes/dumb-indent-mode" '("dumb-"))


;;; Generated autoloads from init/init-linux.el

(register-definition-prefixes "init/init-linux" '("liquid-mode"))


;;; Generated autoloads from init/init-org.el

(register-definition-prefixes "init/init-org" '("JMB/ORG-" "jmb/"))


;;; Generated autoloads from lang/lang-liquid.el

(register-definition-prefixes "lang/lang-liquid" '("liquid-mode"))


;;; Generated autoloads from packages/shopify-liquid-docs.el

(autoload 'shopify-liquid-docs-filters "packages/shopify-liquid-docs"
"Browse Shopify Liquid filters with completion." t)
(autoload 'shopify-liquid-docs-objects "packages/shopify-liquid-docs"
"Browse Shopify Liquid objects with completion." t)
(autoload 'shopify-liquid-docs-tags "packages/shopify-liquid-docs"
"Browse Shopify Liquid tags with completion." t)
(autoload 'shopify-liquid-docs-search "packages/shopify-liquid-docs"
"Search across all Shopify Liquid filters, objects, and tags." t)
(autoload 'shopify-liquid-docs-lookup "packages/shopify-liquid-docs"
"Look up the symbol at point in Shopify Liquid docs." t)
(autoload 'shopify-liquid-docs-refresh "packages/shopify-liquid-docs"
"Re-download and reload all documentation data." t)
(register-definition-prefixes "packages/shopify-liquid-docs" '("shopify-liquid-docs-"))


;;; Generated autoloads from config/config-org.el

(register-definition-prefixes "config/config-org" '("JMB/ORG-" "jmb/"))



;;; Generated autoloads from config/config-agent-shell.el

(register-definition-prefixes "config/config-agent-shell" '("my-agent-shell--codex-acp-auth-method-compat"))


;;; Generated autoloads from config/config-agenda.el

(register-definition-prefixes "config/config-agenda" '("JMB/ORG-" "jmb/"))


;;; Generated autoloads from config/config-llm.el

(register-definition-prefixes "config/config-llm" '("jmb/llm-global-prefix-map" "my-agent-shell--codex-acp-auth-method-compat"))



;;; Generated autoloads from packages/jmb-org-workflow.el

(autoload 'jmb/org-workflow-setup "packages/jmb-org-workflow"
"Configure Org capture, states, agenda, and key bindings." t)
(autoload 'jmb/org-workflow-agenda "packages/jmb-org-workflow"
"Open the workflow agenda." t)
(autoload 'jmb/org-workflow-advance "packages/jmb-org-workflow"
"Choose a valid next state for the current workflow entry." t)
(autoload 'jmb/org-workflow-triage "packages/jmb-org-workflow"
"Clarify, categorize, and deduplicate the current entry." t)
(autoload 'jmb/org-workflow-mark-contacted "packages/jmb-org-workflow"
"Record that responsible parties were contacted and wait for a response." t)
(autoload 'jmb/org-workflow-group-ticket "packages/jmb-org-workflow"
"Assign the current ticket to a worktree group." t)
(autoload 'jmb/org-workflow-dispatch "packages/jmb-org-workflow"
"Apply the urgent/needs-you decision matrix to the current ticket." t)
(autoload 'jmb/org-workflow-provision-worktree "packages/jmb-org-workflow"
"Provision a worktree and tmux session for the current NEXT ticket." t)
(autoload 'jmb/org-workflow-set-dev-port "packages/jmb-org-workflow"
"Prefix the current ticket's tmux session with its development port." t)
(autoload 'jmb/org-workflow-archive "packages/jmb-org-workflow"
"Archive the current DONE or CANCELLED workflow entry." t)
(register-definition-prefixes "packages/jmb-org-workflow" '("jmb/org-workflow-"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
